# Generated by Django 6.1 on 2026-08-10 00:20

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicknotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(db_comment='Date and time when note was made', db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
