# Generated by Django 6.1 on 2026-08-10 00:21

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicknotes', '0002_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
