# Generated by Django 6.1 on 2026-08-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicknotes', '0003_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
